# Generated by Django 5.2.8 on 2025-11-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(default='img/defolt.png', upload_to='images/%Y/%m', verbose_name='Аватарка'),
        ),
    ]
