# Generated by Django 5.2.8 on 2025-11-28 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Quotes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='creator_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='popular',
            name='quotes',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Quotes.quotes'),
        ),
    ]
