# Generated by Django 5.2.8 on 2025-11-14 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotes', '0002_alter_quotes_creator_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='content',
            field=models.TextField(blank=True, verbose_name='quote'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='creator_coment',
            field=models.TextField(blank=True, default=None, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='creator_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
    ]
