# Generated by Django 5.2.8 on 2025-11-29 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotes', '0003_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'quote')},
        ),
        migrations.AddField(
            model_name='like',
            name='type',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], default='like', max_length=7),
        ),
        migrations.AlterField(
            model_name='like',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='Quotes.quotes'),
        ),
        migrations.RemoveField(
            model_name='like',
            name='action',
        ),
    ]
