# Generated by Django 5.2.8 on 2025-12-05 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quotes', '0004_alter_like_unique_together_like_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Popular',
        ),
    ]
