# Generated by Django 5.2.8 on 2025-11-16 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quotes', '0004_alter_quotes_creator_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotes',
            name='creator_coment',
        ),
    ]
