# Generated by Django 5.2.8 on 2025-11-26 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quotes', '0005_remove_quotes_creator_coment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popular',
            name='number_of_views',
        ),
    ]
